# Generated by Django 5.2.16 on 2026-07-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('PRIMARY', 'Primary Guardian'), ('SECONDARY', 'Secondary Guardian'), ('TERTIARY', 'General Contact')], default='PRIMARY', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(blank=True, limit_choices_to={'role': 'GUARDIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_contacts', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resident', 'priority'), name='unique_resident_contact_priority')],
            },
        ),
    ]
