# Generated by Django 5.2.16 on 2026-07-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_block_flat_residentprofile_flat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='block',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='accounts.society'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('society', 'name'), name='unique_society_block'),
        ),
    ]
